name: $VELO farmer

on:
  schedule:
    # Runs at every 5 minutes
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Check $VELO price
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: node src/velo.js
        env:
          DISCORD_WEBHOOK_URL: ${{secrets.DISCORD_WEBHOOK_URL}}
          TARGET_PRICE: ${{secrets.TARGET_PRICE}}
